name: CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'   # Every Sunday midnight
  workflow_dispatch:       # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Step
        run: echo "Building the project..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "Running tests..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    concurrency: production-deploy
    steps:
      - name: Deploy Step
        run: echo "Deploying application..."